name: Rust Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        rust: [stable]

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true

    - name: Build
      run: cargo build --release

    - name: Run tests
      run: cargo test --verbose

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-binary-${{ matrix.os }}
        path: target/release/my-binary

